In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv("train.txt", header=None, sep=';', names=['text', 'emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
emotion_unique = df['emotion'].unique()

In [7]:
emotion_no = {}
i = 1

for emo in emotion_unique:
    emotion_no[emo] = i
    i += 1

df['emotion'] = df['emotion'].map(emotion_no)

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        1
1  i can go from feeling so hopeless to so damned...        1
2   im grabbing a minute to post i feel greedy wrong        2
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        2

In [10]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [11]:
df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]