In [58]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [59]:
df = pd.read_csv("train.txt", header=None, sep=';', names=['text', 'emotion'])

In [60]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [61]:
emotion_unique = df['emotion'].unique()

In [62]:
emotion_no = {}
i = 1

for emo in emotion_unique:
    emotion_no[emo] = i
    i += 1

df['emotion'] = df['emotion'].map(emotion_no)

In [63]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        1
1  i can go from feeling so hopeless to so damned...        1
2   im grabbing a minute to post i feel greedy wrong        2
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        2

In [64]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [65]:
df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [66]:
# 2 Remove Punctuation

import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))


df['text'] = df['text'].apply(remove_punc)

In [67]:
df.sample(5)

                                                    text  emotion
14271  i don t feel a lack of respect or love in the ...        6
12625  i compare myself whether it s to her lifestyle...        1
4301   i feel so horrible that you had to go through ...        1
9745   im still feeling really shitty and undeserving...        1
7669                            i feel so weird about it        5

In [68]:
# 3 Remove Numbers

def remove_num(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new += i
    return new

df['text'] = df['text'].apply(remove_num)

In [71]:
# 4 Remove Emojis

# example for understanding
sentence = "Hello i am your👌 GrandFather🔥"

empty = ""
for i in sentence:
    if not i.isascii():
        empty += i

print(empty)

👌🔥

In [72]:
def remove_emoji(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emoji)

In [24]:
pip install nltk

Requirement already satisfied: nltk in c:\users\sathv\anaconda3\lib\site-packages (3.9.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: click in c:\users\sathv\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\sathv\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sathv\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\sathv\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\sathv\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [32]:
# 5 Removing Stop words we used NLTK

import nltk
nltk.download('punkt_tab')

sentence = """At eight o'clock on Thursday morning Arthur didn't feel very good."""

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sathv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [33]:
sentence

"At eight o'clock on Thursday morning Arthur didn't feel very good."

In [34]:
tokens = nltk.word_tokenize(sentence)
tokens

['At',
 'eight',
 "o'clock",
 'on',
 'Thursday',
 'morning',
 'Arthur',
 'did',
 "n't",
 'feel',
 'very',
 'good',
 '.']

In [37]:
from nltk.corpus import treebank
nltk.download('treebank')

[nltk_data] Downloading package treebank to
[nltk_data]     C:\Users\sathv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\treebank.zip.

True

In [39]:
t = treebank.parsed_sents('wsj_0001.mrg')[0]
t.draw()

In [41]:
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sathv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sathv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [42]:
stop_words = set(stopwords.words('english'))

In [44]:
len(stop_words)

198

In [82]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [95]:
sen = df.loc[1]['text']

tokens = nltk.word_tokenize(sen)
empty = []

for token in tokens:
    if token in stop_words:
        tokens.remove(token)
print(tokens)

['can', 'go', 'feeling', 'hopeless', 'so', 'damned', 'hopeful', 'from', 'around', 'someone', 'cares', 'is', 'awake']