In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
x = df.drop('species', axis=1)
y = df['species']

In [7]:
x.shape, y.shape

((150, 4), (150,))

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [60]:
model_knn = KNeighborsClassifier()
model_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [61]:
model_knn.score(x_test, y_test)

1.0

In [39]:
model_svm = SVC()

In [40]:
model_svm.fit(x_train, y_train)

SVC()

In [41]:
model_svm.score(x_test, y_test)

1.0

# Grid Search CV

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
classifier = GridSearchCV((model_svm), {
    'C':[1, 20, 30, 40],
    'kernel':['rbf', 'linear','sigmoid'],
    'gamma':['auto', 'scale']
}, cv=5, return_train_score=False)

In [45]:
classifier.fit(x, y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 20, 30, 40], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear', 'sigmoid']})

In [48]:
classifier.cv_results_

{'mean_fit_time': array([0.00403547, 0.00273008, 0.00314775, 0.00322638, 0.00302963,
        0.00437317, 0.00315981, 0.00276384, 0.00408359, 0.00290613,
        0.00294318, 0.00424247, 0.00285325, 0.00310574, 0.00406532,
        0.00320859, 0.0043889 , 0.00398579, 0.00222182, 0.0020164 ,
        0.00231819, 0.00212731, 0.00399537, 0.00411472]),
 'std_fit_time': array([1.12686758e-03, 1.03993833e-03, 8.04347904e-04, 9.71940585e-05,
        1.08193437e-04, 1.56550846e-04, 1.12913428e-04, 5.69956807e-04,
        1.27891596e-03, 2.23367871e-04, 8.75248340e-05, 1.27282692e-04,
        4.91781203e-04, 1.61811976e-04, 1.06617462e-04, 2.55575349e-04,
        1.51294867e-03, 4.96782069e-04, 6.53948637e-04, 7.71053921e-04,
        4.25025906e-05, 8.33748886e-04, 6.93075180e-04, 1.22350004e-04]),
 'mean_score_time': array([0.00310259, 0.00192089, 0.00205717, 0.00248303, 0.0022944 ,
        0.00252967, 0.00239296, 0.00188508, 0.00363646, 0.00227642,
        0.0024858 , 0.0025434 , 0.00196404, 0.00224733, 0.00258284,
        0.00229268, 0.00305705, 0.00249953, 0.00153251, 0.00146432,
        0.00140061, 0.00161777, 0.00290132, 0.0024631 ]),
 'std_score_time': array([7.11051240e-04, 5.01957564e-04, 7.52447912e-04, 5.86466284e-05,
        4.62570385e-05, 1.81534818e-04, 5.14362101e-05, 4.53216489e-04,
        2.81582914e-03, 1.35927448e-04, 3.29276391e-04, 1.16274118e-04,
        4.26549146e-04, 1.29002298e-04, 1.29460226e-04, 9.72167244e-05,
        6.50186400e-04, 1.23355423e-04, 5.00674824e-04, 3.42939494e-04,
        3.70970728e-05, 7.24751158e-04, 8.89512553e-04, 2.01736497e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 1, 1, 20, 20, 20, 20, 20, 20, 30, 30, 30,
                    30, 30, 30, 40, 40, 40, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                    'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                    'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                    'auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'sigmoid', 'rbf', 'linear', 'sigmoid',
                    'rbf', 'linear', 'sigmoid', 'rbf', 'linear', 'sigmoid',
                    'rbf', 'linear', 'sigmoid', 'rbf', 'linear', 'sigmoid',
                    'rbf', 'linear', 'sigmoid', 'rbf', 'linear', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.33333333, 0.96666667, 0.96666667,
        0.03333333, 0.96666667, 1.        , 0.33333333, 0.96666667,
        1.        , 0.03333333, 0.96666667, 1.        , 0.33333333,
        0.96666667, 1.        , 0.03333333, 1.        , 1.        ,
        0.33333333, 0.96666667, 1.        , 0.03333333]),
 'split1_test_score': array([1.        , 1.        , 0.1       , 0.96666667, 1.        ,
        0.16666667, 1.        , 1.        , 0.1       , 1.        ,
        1.        , 0.13333333, 1.        , 1.        , 0.1       ,
        1.        , 1.        , 0.13333333, 0.96666667, 1.        ,
        0.1       , 1.        , 1.        , 0.1       ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.        , 0.96666667, 0.96666667,
        0.        , 0.9       , 0.9       , 0.        , 0.96666667,
        0.9       , 0.        , 0.9       , 0.9       , 0.        ,
        0.93333333, 0.9       , 0.        , 0.9       , 0.9       ,
        0.        , 0.93333333, 0.9       , 0.        ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.03333333, 0.93333333, 0.96666667,
        0.1       , 0.96666667, 0.93333333, 0.03333333, 0.96666667,
        0.93333333, 0.03333333, 0.93333333, 0.9       , 0.03333333,
        0.96666667, 0.9       , 0.03333333, 0.93333333, 0.9       ,
        0.03333333, 0.96666667, 0.9       , 0.03333333]),
 'split4_test_score': array([1.        , 1.        , 0.        , 1.        , 1.        ,
        0.03333333, 1.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 1.        , 0.        ,
        1.        , 1.        , 0.        , 1.        , 1.        ,
        0.        , 1.        , 1.        , 0.        ]),
 'mean_test_score': array([0.98      , 0.98      , 0.09333333, 0.96666667, 0.98      ,
        0.06666667, 0.96666667, 0.96666667, 0.09333333, 0.98      ,
        0.96666667, 0.04      , 0.96      , 0.96      , 0.09333333,
        0.97333333, 0.96      , 0.04      , 0.96      , 0.96      ,
        0.09333333, 0.97333333, 0.96      , 0.03333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.12543258, 0.02108185, 0.01632993,
        0.05962848, 0.03651484, 0.0421637 , 0.12543258, 0.01632993,
        0.0421637 , 0.04898979, 0.03887301, 0.04898979, 0.12543258,
        0.02494438, 0.04898979, 0.04898979, 0.03887301, 0.04898979,
        0.12543258, 0.02494438, 0.04898979, 0.03651484]),
 'rank_test_score': array([ 1,  1, 17,  8,  1, 21,  7,  8, 17,  1,  8, 22, 11, 11, 17,  5, 11,
        22, 11, 11, 17,  5, 11, 24], dtype=int32)}

In [66]:
svm_data = pd.DataFrame(data=classifier.cv_results_)

In [67]:
svm_data.head(2)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003072,0.000739,0.002272,0.000625,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1
1,0.003197,0.001206,0.002451,0.000767,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1

In [68]:
svm_data[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1      sigmoid         0.093333
3         1          rbf         0.966667
4         1       linear         0.980000
5         1      sigmoid         0.066667
6        20          rbf         0.966667
7        20       linear         0.966667
8        20      sigmoid         0.093333
9        20          rbf         0.980000
10       20       linear         0.966667
11       20      sigmoid         0.040000
12       30          rbf         0.960000
13       30       linear         0.960000
14       30      sigmoid         0.093333
15       30          rbf         0.973333
16       30       linear         0.960000
17       30      sigmoid         0.040000
18       40          rbf         0.960000
19       40       linear         0.960000
20       40      sigmoid         0.093333
21       40          rbf         0.973333
22       40       linear         0.960000
23       40      sigmoid         0.033333

In [62]:
# gridsearch cv for KNN

classifier2 = GridSearchCV((model_knn), {
    'n_neighbors': [5, 7, 9],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'metric': ['minkowski', 'manhattan']
}, cv=5, return_train_score=False)

In [64]:
classifier2.fit(x, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                         'metric': ['minkowski', 'manhattan'],
                         'n_neighbors': [5, 7, 9],
                         'weights': ['uniform', 'distance']})

In [69]:
knn_data = pd.DataFrame(classifier2.cv_results_)

In [70]:
knn_data.head(2)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002779,0.000831,0.004821,0.000781,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,7
1,0.003506,0.000825,0.004427,0.001373,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,19

In [79]:
knn_data[['param_n_neighbors','param_weights', 'param_metric', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

    param_n_neighbors param_weights param_metric  mean_test_score
3                   7      distance    minkowski         0.980000
2                   7       uniform    minkowski         0.980000
15                  7      distance    minkowski         0.980000
14                  7       uniform    minkowski         0.980000
27                  7      distance    minkowski         0.980000
26                  7       uniform    minkowski         0.980000
24                  5       uniform    minkowski         0.973333
0                   5       uniform    minkowski         0.973333
16                  9       uniform    minkowski         0.973333
12                  5       uniform    minkowski         0.973333
4                   9       uniform    minkowski         0.973333
5                   9      distance    minkowski         0.973333
8                   7       uniform    manhattan         0.973333
28                  9       uniform    minkowski         0.973333
32                  7       uniform    manhattan         0.973333
29                  9      distance    minkowski         0.973333
17                  9      distance    minkowski         0.973333
20                  7       uniform    manhattan         0.973333
1                   5      distance    minkowski         0.966667
10                  9       uniform    manhattan         0.966667
25                  5      distance    minkowski         0.966667
34                  9       uniform    manhattan         0.966667
13                  5      distance    minkowski         0.966667
22                  9       uniform    manhattan         0.966667
7                   5      distance    manhattan         0.960000
6                   5       uniform    manhattan         0.960000
9                   7      distance    manhattan         0.960000
11                  9      distance    manhattan         0.960000
19                  5      distance    manhattan         0.960000
18                  5       uniform    manhattan         0.960000
21                  7      distance    manhattan         0.960000
23                  9      distance    manhattan         0.960000
31                  5      distance    manhattan         0.960000
30                  5       uniform    manhattan         0.960000
33                  7      distance    manhattan         0.960000
35                  9      distance    manhattan         0.960000

# Random Search CV

In [80]:
from sklearn.model_selection import RandomizedSearchCV

classifier_random = RandomizedSearchCV((model_knn), {
    'n_neighbors': [5, 7, 9],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'metric': ['minkowski', 'manhattan']
}, n_iter=10, cv=5, return_train_score=False)

In [81]:
classifier_random.fit(x, y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree'],
                                        'metric': ['minkowski', 'manhattan'],
                                        'n_neighbors': [5, 7, 9],
                                        'weights': ['uniform', 'distance']})

In [82]:
knn_random = pd.DataFrame(classifier_random.cv_results_)

In [84]:
knn_random[['param_n_neighbors','param_weights', 'param_metric', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

   param_n_neighbors param_weights param_metric  mean_test_score
0                  7       uniform    minkowski         0.980000
3                  7       uniform    manhattan         0.973333
6                  5       uniform    minkowski         0.973333
5                  9       uniform    minkowski         0.973333
4                  9       uniform    manhattan         0.966667
2                  5      distance    minkowski         0.966667
8                  5      distance    minkowski         0.966667
1                  5      distance    manhattan         0.960000
7                  9      distance    manhattan         0.960000
9                  5      distance    manhattan         0.960000